dubbo:
  application:
    name: provider
  # 注册中心服务器地址
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  # 协议名称与端口配置
  protocol:
    name: dubbo
    port: 20880
  monitor:
    # 到注册中心中自动发现监控平台
    protocol: registry
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  provider:
    group: student

server:
  port: 8083
