dubbo:
  application:
    name: annotation-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
  protoco;:
    name: dubbo
    port: 20880
#  monitor:
#    protocol: registry
