dubbo:
  application:
    name: comsumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  metadata-report:
      address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry


server:
  port: 8082
